---
# Update apt cache
- name: Update apt cache
  apt:
    update_cache: yes
    cache_valid_time: 3600
  become: yes

# Install required packages
- name: Install required packages
  apt:
    name:
      - curl
      - ca-certificates
    state: present
  become: yes

# Download Docker installation script
- name: Download Docker installation script
  get_url:
    url: https://get.docker.com
    dest: /tmp/get-docker.sh
    mode: '0755'
  become: yes

# Run Docker installation script
- name: Run Docker installation script
  command: sh /tmp/get-docker.sh
  args:
    creates: /usr/bin/docker
  become: yes

# Make sure Docker service is running
- name: Make sure Docker is running
  service:
    name: docker
    state: started
    enabled: yes
  become: yes

# Add user to docker group
- name: Add user to docker group
  user:
    name: "{{ ansible_user }}"
    groups: docker
    append: yes
  become: yes

# Remove Docker installation script
- name: Remove Docker installation script
  file:
    path: /tmp/get-docker.sh
    state: absent
  become: yes 