- name: Install Docker on all servers
  hosts: all
  become: yes
  tasks:
    - name: Update apt cache
      apt:  
        update_cache: yes

    - name: Install required packages
      apt:
        name:
          - curl
          - ca-certificates
        state: present

    - name: Check if Docker is already installed
      command: docker --version
      register: docker_check
      changed_when: false
      failed_when: false

    - name: Download Docker installation script
      shell: curl -fsSL https://get.docker.com -o get-docker.sh
      args:
        chdir: /home/{{ ansible_user }}
      when: docker_check.rc != 0

    - name: Execute Docker installation script
      shell: sh get-docker.sh
      args:
        chdir: /home/{{ ansible_user }}
      register: docker_install
      when: docker_check.rc != 0

    - name: Display Docker installation output
      debug:
        var: docker_install.stdout_lines
      when: docker_install.stdout_lines is defined

    - name: Make sure Docker service is running
      service:
        name: docker
        state: started
        enabled: yes

    - name: Add user to docker group
      user:
        name: "{{ ansible_user }}"
        groups: docker
        append: yes

    - name: Remove Docker installation script
      file:
        path: /home/{{ ansible_user }}/get-docker.sh
        state: absent

    - name: Verify Docker installation
      command: docker --version
      register: docker_version
      changed_when: false

    - name: Display Docker version
      debug:
        var: docker_version.stdout