---
- name: Install Nginx using Docker on VM4 as a reverse proxy
  hosts: proxy
  become: yes
  tasks:
    - name: Create directory for Nginx configuration
      file:
        path: /home/{{ ansible_user }}/nginx-proxy
        state: directory
        mode: '0755'

    - name: Create Nginx configuration file
      copy:
        dest: /home/{{ ansible_user }}/nginx-proxy/nginx.conf
        content: |
          user  nginx;
          worker_processes  auto;
          error_log  /var/log/nginx/error.log;
          pid        /var/run/nginx.pid;

          events {
              worker_connections  1024;
          }

          http {
              include       /etc/nginx/mime.types;
              default_type  application/octet-stream;
              log_format  main  '$remote_addr - $remote_user [$time_local] "$request" '
                              '$status $body_bytes_sent "$http_referer" '
                              '"$http_user_agent" "$http_x_forwarded_for"';
              access_log  /var/log/nginx/access.log  main;
              sendfile        on;
              keepalive_timeout  65;

              upstream django_app {
                  server 192.168.123.10:8000;
                  server 192.168.123.11:8000;
                  server 192.168.123.12:8000;
              }

              server {
                  listen       80;
                  server_name  _;

                  location /static/ {
                      proxy_pass http://192.168.123.10:8000;
                      proxy_set_header Host $host;
                      proxy_set_header X-Real-IP $remote_addr;
                  }

                  location / {
                      proxy_pass http://django_app;
                      proxy_set_header Host $host;
                      proxy_set_header X-Real-IP $remote_addr;
                      proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
                      proxy_redirect off;
                  }
              }
          }
        mode: '0644'

    - name: Run Nginx container
      shell: docker run -d --name nginx-proxy -p 80:80 -v /home/{{ ansible_user }}/nginx-proxy/nginx.conf:/etc/nginx/nginx.conf:ro --restart=always nginx:latest
      args:
        creates: /tmp/nginx_container_created
        
    - name: Touch flag file to indicate container creation
      file:
        path: /tmp/nginx_container_created
        state: touch
        mode: '0644'
        
    - name: Check if Nginx container is running
      shell: docker ps | grep nginx-proxy
      register: container_status
      changed_when: false
      
    - name: Show container status
      debug:
        var: container_status.stdout 