- name: Install Prometheus using Docker on VM4
  hosts: proxy
  become: yes
  tasks:
    - name: Create directories for Prometheus
      file:
        path: "/home/{{ ansible_user }}/{{ item }}"
        state: directory
        mode: '0755'
      with_items:
        - prometheus
        - prometheus/config

    - name: Create data directory for Prometheus
      file:
        path: "/home/{{ ansible_user }}/prometheus/data"
        state: directory
        mode: '0755'

    - name: Create Prometheus configuration
      copy:
        dest: "/home/{{ ansible_user }}/prometheus/config/prometheus.yml"
        content: |
          global:
            scrape_interval: 5s
            evaluation_interval: 5s

          scrape_configs:
            - job_name: 'django'
              static_configs:
                - targets:
                  - '192.168.123.10:80'  # VM1
                  - '192.168.123.11:80'  # VM2
                  - '192.168.123.12:80'  # VM3
              metrics_path: '/metrics'    # Django metrics endpoint

    - name: Stop and remove existing Prometheus container if exists
      docker_container:
        name: prometheus
        state: absent
        force_kill: yes
      ignore_errors: yes

    - name: Pull Prometheus image
      docker_image:
        name: prom/prometheus
        source: pull
        tag: latest

    - name: Run Prometheus container
      docker_container:
        name: prometheus
        image: prom/prometheus:latest
        restart_policy: always
        ports:
          - "9090:9090"
        volumes:
          - "/home/{{ ansible_user }}/prometheus/config:/etc/prometheus"
          - "/home/{{ ansible_user }}/prometheus/data:/prometheus"
        command: 
          - "--config.file=/etc/prometheus/prometheus.yml"
          - "--web.external-url=/prometheus/"
          - "--web.route-prefix=/prometheus/"