---
# Main playbook to deploy the entire infrastructure

- name: Install Docker on all servers
  hosts: all
  become: yes
  roles:
    - { role: common, tags: ['common'] }

- name: Deploy web app on web servers
  hosts: web_servers
  become: yes
  roles:
    - { role: web_app, tags: ['web_app'] }

- name: Configure Nginx reverse proxy
  hosts: proxy
  become: yes
  roles:
    - { role: nginx_proxy, tags: ['nginx_proxy'] } 