---
# Main playbook to deploy the entire infrastructure

# Install Docker on all hosts
- import_playbook: install_docker.yml
  tags: ['common', 'docker']

# Configure Nginx reverse proxy on VM4
- import_playbook: configure_nginx.yml
  tags: ['nginx_proxy'] 