---
# Create directory for Nginx configuration
- name: Create Nginx configuration directory
  file:
    path: /home/{{ ansible_user }}/nginx-proxy/conf.d
    state: directory
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: '0755'
  become: yes

# Copy Nginx configuration
- name: Copy Nginx configuration
  template:
    src: default.conf.j2
    dest: /home/{{ ansible_user }}/nginx-proxy/conf.d/default.conf
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: '0644'

# Run Nginx container with the configuration
- name: Run Nginx proxy container
  docker_container:
    name: nginx_proxy
    image: nginx:alpine
    state: started
    restart_policy: always
    published_ports:
      - "80:80"
    volumes:
      - /home/{{ ansible_user }}/nginx-proxy/conf.d:/etc/nginx/conf.d 