name: CI/CD Pipeline

on:
  push:
    branches: [master]
    paths:
      - 'web-app/**'  # Only trigger when web-app directory has changes
  pull_request:
    branches: [master]
    paths:
      - 'web-app/**'  # Only trigger when web-app directory has changes

jobs:
  build-and-push:
    runs-on: ubuntu-latest  # Using GitHub-hosted runner for build & push
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          context: ./web-app
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/django-web-app:latest